### ISSUE TITLE
Support for multiple nested go.mod files

### ISSUE THREAD

**Issue by sbp-bvanb** [030/gomod-go-version-updater-action#95]
path/go.mod
path/somewhere/else/go.mod

**Comment by sbp-bvanb** [comment]
It turned out that the `go mod tidy` step works only for single go.mod files:

```
    - uses: actions/setup-go@v5.3.0
      with:
        go-version-file: "go.mod"
        cache: false
    - run: |
        git config --global url.https://${{ inputs.github-token-for-downloading-private-go-modules }}@github.com/.insteadOf https://github.com/
      shell: bash
      if: ${{ inputs.github-token-for-downloading-private-go-modules != '' }}
    - name: go mod tidy
      run: |
        go mod tidy
      shell: bash
    - name: commit and force push if needed
      run: |
        if [ -n "$(git status --porcelain)" ]; then echo "There are uncommitted changes."; else echo "No changes to commit." && exit 0; fi

        git add .
        git commit --amend --no-edit
        git push origin ${GOMOD_GO_VERSION_UPDATER_ACTION_BRANCH} -f
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
```


The second finding is that the nested go.mod files are not commited.
